meta_title:
    label: initbiz.seostorm::lang.form.general.meta_title_label
    type: text
    span: full
    tab: initbiz.seostorm::lang.form.general.tab_meta
    trans: true
    attributes:
        data-counter: 1
        data-min: 30
        data-max: 60
        data-seo: title

meta_description:
    label: initbiz.seostorm::lang.form.general.meta_description_label
    type: textarea
    size: tiny
    span: full
    tab: initbiz.seostorm::lang.form.general.tab_meta
    cssClass: char-counter
    trans: true
    attributes:
        data-counter: 1
        data-min: 100
        data-max: 160
        data-seo: description

canonical_url:
    label: initbiz.seostorm::lang.form.general.canonical_url_label
    commentAbove: initbiz.seostorm::lang.form.general.canonical_url_comment
    tab: initbiz.seostorm::lang.form.general.tab_meta
    type: text
    span: full
    trans: true

robot_index:
    label: initbiz.seostorm::lang.form.general.robot_index_label
    commentAbove: initbiz.seostorm::lang.form.general.robot_index_comment
    tab: initbiz.seostorm::lang.form.general.tab_meta
    type: balloon-selector
    options:
        index: Index
        noindex: Noindex
        '': initbiz.seostorm::lang.form.general.robot_empty
    span: left
    default: index

robot_follow:
    label: initbiz.seostorm::lang.form.general.robot_follow_label
    commentAbove: initbiz.seostorm::lang.form.general.robot_follow_comment
    tab: initbiz.seostorm::lang.form.general.tab_meta
    type: balloon-selector
    options:
        follow: Follow
        nofollow: Nofollow
        '': initbiz.seostorm::lang.form.general.robot_empty
    span: right
    default: follow

robot_advanced:
    label: initbiz.seostorm::lang.form.general.robot_advanced_label
    commentAbove: initbiz.seostorm::lang.form.general.robot_advanced_comment
    tab: initbiz.seostorm::lang.form.general.tab_meta
    span: left
